In [75]:
import nflreadpy as nfl
import pandas as pd
import os
from pathlib import Path
import numpy as np

In [3]:
team_stats = nfl.load_team_stats(seasons=[2025])
team_stats

shape: (186, 102)
┌────────┬──────┬──────┬─────────────┬───┬──────────┬─────────────┬──────────────┬───────────────┐
│ season ┆ week ┆ team ┆ season_type ┆ … ┆ gwfg_att ┆ gwfg_missed ┆ gwfg_blocked ┆ gwfg_distance │
│ ---    ┆ ---  ┆ ---  ┆ ---         ┆   ┆ ---      ┆ ---         ┆ ---          ┆ ---           │
│ i32    ┆ i32  ┆ str  ┆ str         ┆   ┆ i32      ┆ i32         ┆ i32          ┆ i32           │
╞════════╪══════╪══════╪═════════════╪═══╪══════════╪═════════════╪══════════════╪═══════════════╡
│ 2025   ┆ 1    ┆ ARI  ┆ REG         ┆ … ┆ 0        ┆ 0           ┆ 0            ┆ 0             │
│ 2025   ┆ 1    ┆ ATL  ┆ REG         ┆ … ┆ 0        ┆ 0           ┆ 0            ┆ 0             │
│ 2025   ┆ 1    ┆ BAL  ┆ REG         ┆ … ┆ 0        ┆ 0           ┆ 0            ┆ 0             │
│ 2025   ┆ 1    ┆ BUF  ┆ REG         ┆ … ┆ 1        ┆ 0           ┆ 0            ┆ 32            │
│ 2025   ┆ 1    ┆ CAR  ┆ REG         ┆ … ┆ 0        ┆ 0           ┆ 0            ┆ 0             │
│ …      ┆ …    ┆ …    ┆ …           ┆ … ┆ …        ┆ …           ┆ …            ┆ …             │
│ 2025   ┆ 6    ┆ SEA  ┆ REG         ┆ … ┆ 0        ┆ 0           ┆ 0            ┆ 0             │
│ 2025   ┆ 6    ┆ SF   ┆ REG         ┆ … ┆ 0        ┆ 0           ┆ 0            ┆ 0             │
│ 2025   ┆ 6    ┆ TB   ┆ REG         ┆ … ┆ 0        ┆ 0           ┆ 0            ┆ 0             │
│ 2025   ┆ 6    ┆ TEN  ┆ REG         ┆ … ┆ 0        ┆ 0           ┆ 0            ┆ 0             │
│ 2025   ┆ 6    ┆ WAS  ┆ REG         ┆ … ┆ 0        ┆ 0           ┆ 0            ┆ 0             │
└────────┴──────┴──────┴─────────────┴───┴──────────┴─────────────┴──────────────┴───────────────┘

In [14]:
nfl_2024 = nfl.load_schedules([2024])
nfl_2024

shape: (285, 46)
┌─────────────┬────────┬───────────┬──────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ game_id     ┆ season ┆ game_type ┆ week ┆ … ┆ home_coach  ┆ referee    ┆ stadium_id ┆ stadium    │
│ ---         ┆ ---    ┆ ---       ┆ ---  ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│ str         ┆ i64    ┆ str       ┆ i64  ┆   ┆ str         ┆ str        ┆ str        ┆ str        │
╞═════════════╪════════╪═══════════╪══════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 2024_01_BAL ┆ 2024   ┆ REG       ┆ 1    ┆ … ┆ Andy Reid   ┆ Shawn      ┆ KAN00      ┆ GEHA Field │
│ _KC         ┆        ┆           ┆      ┆   ┆             ┆ Hochuli    ┆            ┆ at         │
│             ┆        ┆           ┆      ┆   ┆             ┆            ┆            ┆ Arrowhead  │
│             ┆        ┆           ┆      ┆   ┆             ┆            ┆            ┆ Stadiu…    │
│ 2024_01_GB_ ┆ 2024   ┆ REG       ┆ 1    ┆ … ┆ Nick        ┆ Ron        ┆ SAO00      ┆ Arena Cori │
│ PHI         ┆        ┆           ┆      ┆   ┆ Sirianni    ┆ Torbert    ┆            ┆ nthians    │
│ 2024_01_PIT ┆ 2024   ┆ REG       ┆ 1    ┆ … ┆ Raheem      ┆ Brad       ┆ ATL97      ┆ Mercedes-B │
│ _ATL        ┆        ┆           ┆      ┆   ┆ Morris      ┆ Rogers     ┆            ┆ enz        │
│             ┆        ┆           ┆      ┆   ┆             ┆            ┆            ┆ Stadium    │
│ 2024_01_ARI ┆ 2024   ┆ REG       ┆ 1    ┆ … ┆ Sean        ┆ Tra Blake  ┆ BUF00      ┆ New Era    │
│ _BUF        ┆        ┆           ┆      ┆   ┆ McDermott   ┆            ┆            ┆ Field      │
│ 2024_01_TEN ┆ 2024   ┆ REG       ┆ 1    ┆ … ┆ Matt        ┆ Shawn      ┆ CHI98      ┆ Soldier    │
│ _CHI        ┆        ┆           ┆      ┆   ┆ Eberflus    ┆ Smith      ┆            ┆ Field      │
│ …           ┆ …      ┆ …         ┆ …    ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ 2024_20_LA_ ┆ 2024   ┆ DIV       ┆ 20   ┆ … ┆ Nick        ┆ Shawn      ┆ PHI00      ┆ Lincoln    │
│ PHI         ┆        ┆           ┆      ┆   ┆ Sirianni    ┆ Smith      ┆            ┆ Financial  │
│             ┆        ┆           ┆      ┆   ┆             ┆            ┆            ┆ Field      │
│ 2024_20_BAL ┆ 2024   ┆ DIV       ┆ 20   ┆ … ┆ Sean        ┆ Carl       ┆ BUF00      ┆ New Era    │
│ _BUF        ┆        ┆           ┆      ┆   ┆ McDermott   ┆ Cheffers   ┆            ┆ Field      │
│ 2024_21_WAS ┆ 2024   ┆ CON       ┆ 21   ┆ … ┆ Nick        ┆ Shawn      ┆ PHI00      ┆ Lincoln    │
│ _PHI        ┆        ┆           ┆      ┆   ┆ Sirianni    ┆ Hochuli    ┆            ┆ Financial  │
│             ┆        ┆           ┆      ┆   ┆             ┆            ┆            ┆ Field      │
│ 2024_21_BUF ┆ 2024   ┆ CON       ┆ 21   ┆ … ┆ Andy Reid   ┆ Clete      ┆ KAN00      ┆ GEHA Field │
│ _KC         ┆        ┆           ┆      ┆   ┆             ┆ Blakeman   ┆            ┆ at         │
│             ┆        ┆           ┆      ┆   ┆             ┆            ┆            ┆ Arrowhead  │
│             ┆        ┆           ┆      ┆   ┆             ┆            ┆            ┆ Stadiu…    │
│ 2024_22_KC_ ┆ 2024   ┆ SB        ┆ 22   ┆ … ┆ Nick        ┆ Ron        ┆ NOR00      ┆ Mercedes-B │
│ PHI         ┆        ┆           ┆      ┆   ┆ Sirianni    ┆ Torbert    ┆            ┆ enz        │
│             ┆        ┆           ┆      ┆   ┆             ┆            ┆            ┆ Superdome  │
└─────────────┴────────┴───────────┴──────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [6]:
pbp = nfl.load_pbp(seasons=[2024])

In [28]:
pbp2 = nfl.load_pbp(seasons=[2024])
pbp2.head()

shape: (5, 372)
┌─────────┬────────────┬────────────┬───────────┬───┬────────────┬──────────┬──────────┬───────────┐
│ play_id ┆ game_id    ┆ old_game_i ┆ home_team ┆ … ┆ xyac_succe ┆ xyac_fd  ┆ xpass    ┆ pass_oe   │
│ ---     ┆ ---        ┆ d          ┆ ---       ┆   ┆ ss         ┆ ---      ┆ ---      ┆ ---       │
│ f64     ┆ str        ┆ ---        ┆ str       ┆   ┆ ---        ┆ f64      ┆ f64      ┆ f64       │
│         ┆            ┆ str        ┆           ┆   ┆ f64        ┆          ┆          ┆           │
╞═════════╪════════════╪════════════╪═══════════╪═══╪════════════╪══════════╪══════════╪═══════════╡
│ 1.0     ┆ 2024_01_AR ┆ 2024090801 ┆ BUF       ┆ … ┆ null       ┆ null     ┆ null     ┆ null      │
│         ┆ I_BUF      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 40.0    ┆ 2024_01_AR ┆ 2024090801 ┆ BUF       ┆ … ┆ null       ┆ null     ┆ null     ┆ null      │
│         ┆ I_BUF      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 61.0    ┆ 2024_01_AR ┆ 2024090801 ┆ BUF       ┆ … ┆ null       ┆ null     ┆ 0.456761 ┆ -45.67610 │
│         ┆ I_BUF      ┆            ┆           ┆   ┆            ┆          ┆          ┆ 3         │
│ 83.0    ┆ 2024_01_AR ┆ 2024090801 ┆ BUF       ┆ … ┆ 0.509778   ┆ 0.363807 ┆ 0.576656 ┆ 42.334431 │
│         ┆ I_BUF      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 108.0   ┆ 2024_01_AR ┆ 2024090801 ┆ BUF       ┆ … ┆ 0.668478   ┆ 0.25514  ┆ 0.426443 ┆ 57.35569  │
│         ┆ I_BUF      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
└─────────┴────────────┴────────────┴───────────┴───┴────────────┴──────────┴──────────┴───────────┘

In [11]:
ngs = nfl.load_nextgen_stats(seasons=[2024], stat_type='receiving')

ngs

shape: (1_435, 23)
┌────────┬─────────────┬──────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ season ┆ season_type ┆ week ┆ player_dis ┆ … ┆ player_fir ┆ player_las ┆ player_jer ┆ player_sho │
│ ---    ┆ ---         ┆ ---  ┆ play_name  ┆   ┆ st_name    ┆ t_name     ┆ sey_number ┆ rt_name    │
│ i32    ┆ str         ┆ i32  ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│        ┆             ┆      ┆ str        ┆   ┆ str        ┆ str        ┆ i32        ┆ str        │
╞════════╪═════════════╪══════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2024   ┆ REG         ┆ 0    ┆ Ray-Ray    ┆ … ┆ Ray-Ray    ┆ McCloud    ┆ 34         ┆ R.McCloud  │
│        ┆             ┆      ┆ McCloud    ┆   ┆            ┆            ┆            ┆            │
│ 2024   ┆ REG         ┆ 0    ┆ Marvin     ┆ … ┆ Marvin     ┆ Mims       ┆ 19         ┆ M.Mims     │
│        ┆             ┆      ┆ Mims       ┆   ┆            ┆            ┆            ┆            │
│ 2024   ┆ REG         ┆ 0    ┆ Tutu       ┆ … ┆ Chatarius  ┆ Atwell     ┆ 5          ┆ T.Atwell   │
│        ┆             ┆      ┆ Atwell     ┆   ┆            ┆            ┆            ┆            │
│ 2024   ┆ REG         ┆ 0    ┆ Greg       ┆ … ┆ Greg       ┆ Dortch     ┆ 4          ┆ G.Dortch   │
│        ┆             ┆      ┆ Dortch     ┆   ┆            ┆            ┆            ┆            │
│ 2024   ┆ REG         ┆ 0    ┆ Troy       ┆ … ┆ Troy       ┆ Franklin   ┆ 16         ┆ T.Franklin │
│        ┆             ┆      ┆ Franklin   ┆   ┆            ┆            ┆            ┆            │
│ …      ┆ …           ┆ …    ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2024   ┆ POST        ┆ 23   ┆ DeAndre    ┆ … ┆ DeAndre    ┆ Hopkins    ┆ 8          ┆ D.Hopkins  │
│        ┆             ┆      ┆ Hopkins    ┆   ┆            ┆            ┆            ┆            │
│ 2024   ┆ POST        ┆ 23   ┆ DeVonta    ┆ … ┆ DeVonta    ┆ Smith      ┆ 6          ┆ D.Smith    │
│        ┆             ┆      ┆ Smith      ┆   ┆            ┆            ┆            ┆            │
│ 2024   ┆ POST        ┆ 23   ┆ Travis     ┆ … ┆ Travis     ┆ Kelce      ┆ 87         ┆ T.Kelce    │
│        ┆             ┆      ┆ Kelce      ┆   ┆            ┆            ┆            ┆            │
│ 2024   ┆ POST        ┆ 23   ┆ Marquise   ┆ … ┆ Marquise   ┆ Brown      ┆ 5          ┆ M.Brown    │
│        ┆             ┆      ┆ Brown      ┆   ┆            ┆            ┆            ┆            │
│ 2024   ┆ POST        ┆ 23   ┆ A.J. Brown ┆ … ┆ Arthur     ┆ Brown      ┆ 11         ┆ A.Brown    │
└────────┴─────────────┴──────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [15]:
injuries = nfl.load_injuries([2024])
injuries.write_parquet("data/raw/test_data_2.parquet")

In [196]:
###populating

def fetch_and_save(years, base_path='data/raw'):
    os.makedirs(base_path, exist_ok=True)
    
    for year in years:
        print(f'fetching {year} seasons ')
        season_folder = os.path.join(base_path,str(year))
        os.makedirs(season_folder, exist_ok=True)
        
        # pbp = nfl.load_pbp(seasons=[year])
        # pbp.write_parquet(os.path.join(season_folder,"pbp.parquet"))
        
        # team_stats = nfl.load_team_stats(seasons=[year])
        # team_stats.write_parquet(os.path.join(season_folder,'team_stats.parquet'))
        
        # games = nfl.load_schedules(seasons=[year])
        # games.write_parquet(os.path.join(season_folder, "games.parquet"))

        # Officials (referees)
        refs = nfl.load_officials(seasons=[year])
        refs.write_parquet(os.path.join(season_folder, "officials.parquet"))
        
        
        # injuries = nfl.load_injuries(seasons=[year])
        # injuries.write_parquet(os.path.join(season_folder, "injuries.parquet"))

        snaps = nfl.load_snap_counts(seasons=[year])
        snaps.write_parquet(os.path.join(season_folder, "snap_counts.parquet"))
        
        weekly_rosters = nfl.load_rosters_weekly(seasons=[year])
        weekly_rosters.write_parquet(os.path.join(season_folder,"weekly_rosters.parquet"))
       

        print(f"{year} saved in {season_folder}")

In [197]:
years = list(range(2015, 2025))
fetch_and_save([2025])

fetching 2025 seasons
2025 saved in data/raw\2025

In [26]:
years = sorted(int(p.name) for p in Path("data/raw").iterdir() if p.is_dir())

def load_year(y, name): return pd.read_parquet(f"data/raw/{y}/{name}.parquet")

for year in years:
    print(type(load_year(year,"games")))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

### tmr i need to loop thru each files data frames and filter them to regular season only 

this will involve reading each file and filtering by the game_type (confirm if this is a thing) column of each table 
then pd output to parquet and from there we have reg seaosn data for each game 
then need to handle replacing team names with current ones

i can cluster play by play, offense plays aggregated by team (and defense), can clean those columsn and add calculated fields such as create a score between the outcome or pattern of play for each team (first 15 plays on offense), defense vs play type score, and then cluster using that feature to also show similar performing teams (may need to be revamped).

In [ ]:
###populating

def fetch_and_save(years, base_path='data/raw'):
    os.makedirs(base_path, exist_ok=True)
    
    for year in years:
        print(f'fetching {year} seasons ')
        season_folder = os.path.join(base_path,str(year))
        os.makedirs(season_folder, exist_ok=True)
        
        # pbp = nfl.load_pbp(seasons=[year])
        # pbp.write_parquet(os.path.join(season_folder,"pbp.parquet"))
        
        # team_stats = nfl.load_team_stats(seasons=[year])
        # team_stats.write_parquet(os.path.join(season_folder,'team_stats.parquet'))
        
        # games = nfl.load_schedules(seasons=[year])
        # games.write_parquet(os.path.join(season_folder, "games.parquet"))

        # # Officials (referees)
        # refs = nfl.load_officials(seasons=[year])
        # refs.write_parquet(os.path.join(season_folder, "officials.parquet"))
        
        
        injuries = nfl.load_injuries(seasons=[year])
        injuries.write_parquet(os.path.join(season_folder, "injuries.parquet"))

        snaps = nfl.load_snap_counts(seasons=[year])
        snaps.write_parquet(os.path.join(season_folder, "snap_counts.parquet"))
        
        weekly_rosters = nfl.load_rosters_weekly(seasons=[year])
        weekly_rosters.write_parquet(os.path.join(season_folder,"weekly_rosters.parquet"))
       

        print(f"{year} saved in {season_folder}")
        
        
years = sorted(int(p.name) for p in Path("data/raw").iterdir() if p.is_dir())

def load_year(y, name): return pd.read_parquet(f"data/raw/{y}/{name}.parquet")

for year in years:
    print(type(load_year(year,"games")))

In [198]:
team_stats_2015 = pd.read_parquet(f"data/raw/{'2025'}/{'team_stats'}.parquet")
team_stats_2015_regszn = team_stats_2015[team_stats_2015['season_type']=='REG']
print(team_stats_2015_regszn.shape)
team_stats_2015_regszn

(188, 102)

AttributeError: 'Index' object has no attribute '_format_flat'

     season  week team season_type opponent_team  completions  attempts  \
0      2025     1  ARI         REG            NO           21        29
1      2025     1  ATL         REG            TB           27        42
2      2025     1  BAL         REG           BUF           14        19
3      2025     1  BUF         REG           BAL           33        46
4      2025     1  CAR         REG           JAX           18        35
..      ...   ...  ...         ...           ...          ...       ...
183    2025     6   TB         REG            SF           17        23
184    2025     6  TEN         REG            LV           26        38
185    2025     6  WAS         REG           CHI           19        26
186    2025     7  CIN         REG           PIT           31        47
187    2025     7  PIT         REG           CIN           23        34

     passing_yards  passing_tds  passing_interceptions  ...  pat_made  \
0              163            2                      0  ...         2
1              298            1                      0  ...         2
2              209            2                      0  ...         4
3              394            2                      0  ...         2
4              154            1                      2  ...         1
..             ...          ...                    ...  ...       ...
183            256            2                      0  ...         3
184            222            1                      1  ...         1
185            211            3                      1  ...         3
186            342            3                      0  ...         3
187            249            4                      2  ...         4

     pat_att  pat_missed  pat_blocked  pat_pct  gwfg_made  gwfg_att  \
0          2           0            0      1.0          0         0
1          2           0            0      1.0          0         0
2          5           1            0      0.8          0         0
3          2           0            0      1.0          1         1
4          1           0            0      1.0          0         0
..       ...         ...          ...      ...        ...       ...
183        3           0            0      1.0          0         0
184        1           0            0      1.0          0         0
185        3           0            0      1.0          0         0
186        3           0            0      1.0          1         1
187        4           0            0      1.0          0         0

     gwfg_missed  gwfg_blocked  gwfg_distance
0              0             0              0
1              0             0              0
2              0             0              0
3              0             0             32
4              0             0              0
..           ...           ...            ...
183            0             0              0
184            0             0              0
185            0             0              0
186            0             0             36
187            0             0              0

[188 rows x 102 columns]

In [200]:

## new dataframe called offensive_team_stats_weekly stats
## append off columns/columns that wll be used
## for each week and team,
## calculate off stats and add them to new columns

df = team_stats_2015_regszn.copy(deep=True)

grouped_by_team_week = df.sort_values(by=['team', 'week'],ascending=True)
grouped_by_team_week

# team_and_week = df.groupby(['week','team'])

# team_and_week

AttributeError: 'Index' object has no attribute '_format_flat'

     season  week team season_type opponent_team  completions  attempts  \
0      2025     1  ARI         REG            NO           21        29
32     2025     2  ARI         REG           CAR           17        25
64     2025     3  ARI         REG            SF           22        35
96     2025     4  ARI         REG           SEA           27        41
128    2025     5  ARI         REG           TEN           23        32
..      ...   ...  ...         ...           ...          ...       ...
63     2025     2  WAS         REG            GB           24        42
95     2025     3  WAS         REG            LV           15        21
127    2025     4  WAS         REG           ATL           16        27
155    2025     5  WAS         REG           LAC           15        26
185    2025     6  WAS         REG           CHI           19        26

     passing_yards  passing_tds  passing_interceptions  ...  pat_made  \
0              163            2                      0  ...         2
32             220            1                      1  ...         3
64             159            1                      0  ...         1
96             200            2                      2  ...         2
128            220            0                      0  ...         3
..             ...          ...                    ...  ...       ...
63             200            2                      0  ...         1
95             207            1                      0  ...         5
127            156            2                      1  ...         1
155            231            1                      0  ...         3
185            211            3                      1  ...         3

     pat_att  pat_missed  pat_blocked  pat_pct  gwfg_made  gwfg_att  \
0          2           0            0      1.0          0         0
32         3           0            0      1.0          0         0
64         1           0            0      1.0          0         0
96         2           0            0      1.0          0         0
128        3           0            0      1.0          0         0
..       ...         ...          ...      ...        ...       ...
63         1           0            0      1.0          0         0
95         5           0            0      1.0          0         0
127        1           0            0      1.0          0         0
155        3           0            0      1.0          0         0
185        3           0            0      1.0          0         0

     gwfg_missed  gwfg_blocked  gwfg_distance
0              0             0              0
32             0             0              0
64             0             0              0
96             0             0              0
128            0             0              0
..           ...           ...            ...
63             0             0              0
95             0             0              0
127            0             0              0
155            0             0              0
185            0             0              0

[188 rows x 102 columns]

In [201]:
total_att_carr = grouped_by_team_week['attempts'] + grouped_by_team_week['carries']

attempts = grouped_by_team_week['attempts']


grouped_by_team_week['pass_rate'] = np.divide(
    attempts,
    total_att_carr,
    out= np.zeros_like(attempts, dtype=float),
    where= total_att_carr != 0
)


grouped_by_team_week['yards_per_att'] = np.divide(
    grouped_by_team_week['passing_yards'],
    attempts,
    out= np.zeros_like(attempts, dtype=float),
    where=  attempts!= 0)


grouped_by_team_week['td_rate'] = np.divide(
    grouped_by_team_week['passing_tds'],
    attempts,
    out= np.zeros_like(attempts, dtype=float),
    where= attempts!=0
    )


grouped_by_team_week['int_rate'] = np.divide(
    grouped_by_team_week['passing_interceptions'],
    attempts,
    out= np.zeros_like(attempts, dtype=float),
    where= attempts!=0
    )

att_sacks_suff = attempts + grouped_by_team_week['sacks_suffered']

grouped_by_team_week['sack_rate'] = np.divide(
    grouped_by_team_week['sacks_suffered'],
    att_sacks_suff,
    out= np.zeros_like(attempts, dtype=float),
    where= attempts!=0
    )

grouped_by_team_week['rush_ypc'] = np.divide(
    grouped_by_team_week['rushing_yards'],
    grouped_by_team_week['carries'],
    out= np.zeros_like(attempts, dtype=float),
    where= attempts!=0
    )

first_downs = grouped_by_team_week['passing_first_downs'] + grouped_by_team_week['rushing_first_downs']

grouped_by_team_week['explosive_proxy'] = np.divide(
    first_downs,
    total_att_carr,
    out= np.zeros_like(attempts, dtype=float),
    where= attempts!=0
    )
grouped_by_team_week['off_epa'] = grouped_by_team_week['passing_epa'] + grouped_by_team_week['rushing_epa'] + grouped_by_team_week['receiving_epa']

 
grouped_by_team_week['epa_per_play'] = np.divide(
    grouped_by_team_week['off_epa'],
    total_att_carr,
    out= np.zeros_like(attempts, dtype=float),
    where= attempts!=0
    )
 


grouped_by_team_week['adot'] = np.divide(
    grouped_by_team_week['passing_air_yards'],
    attempts,
    out= np.zeros_like(attempts, dtype=float),
    where= attempts!=0
    )

grouped_by_team_week['yac_per_rec'] =  np.divide(
    grouped_by_team_week['passing_yards_after_catch'],
    grouped_by_team_week['receptions'],
    out= np.zeros_like(attempts, dtype=float),
    where= attempts!=0
    )

In [202]:
grouped_by_team_week

AttributeError: 'Index' object has no attribute '_format_flat'

     season  week team season_type opponent_team  completions  attempts  \
0      2025     1  ARI         REG            NO           21        29
32     2025     2  ARI         REG           CAR           17        25
64     2025     3  ARI         REG            SF           22        35
96     2025     4  ARI         REG           SEA           27        41
128    2025     5  ARI         REG           TEN           23        32
..      ...   ...  ...         ...           ...          ...       ...
63     2025     2  WAS         REG            GB           24        42
95     2025     3  WAS         REG            LV           15        21
127    2025     4  WAS         REG           ATL           16        27
155    2025     5  WAS         REG           LAC           15        26
185    2025     6  WAS         REG           CHI           19        26

     passing_yards  passing_tds  passing_interceptions  ...  yards_per_att  \
0              163            2                      0  ...       5.620690
32             220            1                      1  ...       8.800000
64             159            1                      0  ...       4.542857
96             200            2                      2  ...       4.878049
128            220            0                      0  ...       6.875000
..             ...          ...                    ...  ...            ...
63             200            2                      0  ...       4.761905
95             207            1                      0  ...       9.857143
127            156            2                      1  ...       5.777778
155            231            1                      0  ...       8.884615
185            211            3                      1  ...       8.115385

      td_rate  int_rate  sack_rate  rush_ypc  explosive_proxy    off_epa  \
0    0.068966  0.000000   0.147059  5.407407         0.303571  11.460992
32   0.040000  0.040000   0.038462  3.727273         0.319149  14.376126
64   0.028571  0.000000   0.027778  3.785714         0.238095   1.296078
96   0.048780  0.048780   0.127660  5.235294         0.258621   0.779984
128  0.000000  0.000000   0.085714  5.793103         0.295082   4.022022
..        ...       ...        ...       ...              ...        ...
63   0.047619  0.000000   0.086957  2.684211         0.213115 -12.749786
95   0.047619  0.000000   0.045455  6.281250         0.283019  30.342750
127  0.074074  0.037037   0.068966  6.681818         0.326531  10.488719
155  0.038462  0.000000   0.037037  5.821429         0.333333  29.069761
185  0.115385  0.038462   0.103448  4.000000         0.333333   8.801267

     epa_per_play       adot  yac_per_rec
0        0.204661   5.724138     4.761905
32       0.305875   6.400000     6.647059
64       0.020573   5.057143     4.181818
96       0.013448   5.804878     4.629630
128      0.065935   6.531250     5.000000
..            ...        ...          ...
63      -0.209013   6.642857     4.458333
95       0.572505   7.523810     7.533333
127      0.214055  10.592593     1.437500
155      0.538329   9.192308     7.333333
185      0.154408   8.153846     3.684211

[188 rows x 113 columns]

In [203]:
games_odds = pd.read_parquet(f"data/raw/nfl_betting_data.parquet")

print(games_odds)

      season  game_date         team          opp  week   loc  spread  total  \
0       2025 2025-10-13   Washington      Chicago     6  Home    -5.5   49.0
1       2025 2025-10-13      Chicago   Washington     6  Away     5.5   49.0
2       2025 2025-10-13      Atlanta      Buffalo     6  Home     3.5   49.5
3       2025 2025-10-13      Buffalo      Atlanta     6  Away    -3.5   49.5
4       2025 2025-10-12  Kansas City      Detroit     6  Home    -2.5   51.0
...      ...        ...          ...          ...   ...   ...     ...    ...
5427    2015 2015-09-13  Kansas City      Houston     1  Away    -1.0   41.0
5428    2015 2015-09-13      Chicago    Green Bay     1  Home     6.0   48.5
5429    2015 2015-09-13    Green Bay      Chicago     1  Away    -6.0   48.5
5430    2015 2015-09-10  New England   Pittsburgh     1  Home    -7.0   51.0
5431    2015 2015-09-10   Pittsburgh  New England     1  Away     7.0   51.0

      money_line  conf_game  ...       game_type prev_result days_of_rest  \
0           -250       True  ...  Regular Season         Win          8.0
1            200       True  ...  Regular Season         Win         15.0
2            177      False  ...  Regular Season         Win         15.0
3           -210      False  ...  Regular Season        Loss          8.0
4           -150      False  ...  Regular Season        Loss          6.0
...          ...        ...  ...             ...         ...          ...
5427        -115       True  ...  Regular Season  First Game          NaN
5428         230       True  ...  Regular Season  First Game          NaN
5429        -290       True  ...  Regular Season  First Game          NaN
5430        -360       True  ...  Regular Season  First Game          NaN
5431         280       True  ...  Regular Season  First Game          NaN

      opp_days_of_rest  rest_advantage  score mov  ats_margin  combined_pts  \
0                 15.0            -7.0  24-25  -1        -6.5            49
1                  8.0             7.0  25-24   1         6.5            49
2                  8.0             7.0  24-14  10        13.5            38
3                 15.0            -7.0  14-24 -10       -13.5            38
4                  7.0            -1.0  30-17  13        10.5            47
...                ...             ...    ...  ..         ...           ...
5427               NaN             0.0  27-20   7         6.0            47
5428               NaN             0.0  23-31  -8        -2.0            54
5429               NaN             0.0  31-23   8         2.0            54
5430               NaN             0.0  28-21   7         0.0            49
5431               NaN             0.0  21-28  -7         0.0            49

      OU_margin
0           0.0
1           0.0
2         -11.5
3         -11.5
4          -4.0
...         ...
5427        6.0
5428        5.5
5429        5.5
5430       -2.0
5431       -2.0

[5432 rows x 21 columns]

In [114]:
# See all unique team names
unique_teams = set(games_odds['team'].unique()) | set(games_odds['opp'].unique())
print("All unique teams in data:")
for team in sorted(unique_teams):
    print(f"  '{team}'")

# Check which ones are missing from your mapping
missing = unique_teams - set(TEAM_TO_ABBR.keys())
if missing:
    print("\n⚠️ Teams not in mapping:")
    for team in sorted(missing):
        print(f"  '{team}'")

All unique teams in data:
  'Arizona'
  'Atlanta'
  'Baltimore'
  'Buffalo'
  'Carolina'
  'Chicago'
  'Cincinnati'
  'Cleveland'
  'Dallas'
  'Denver'
  'Detroit'
  'Green Bay'
  'Houston'
  'Indianapolis'
  'Jacksonville'
  'Kansas City'
  'LA Chargers'
  'LA Rams'
  'Las Vegas'
  'Los Angeles'
  'Miami'
  'Minnesota'
  'NY Giants'
  'NY Jets'
  'New England'
  'New Orleans'
  'Oakland'
  'Philadelphia'
  'Pittsburgh'
  'San Diego'
  'San Francisco'
  'Seattle'
  'St Louis'
  'Tampa Bay'
  'Tennessee'
  'Washington'

In [118]:
TEAM_TO_ABBR = {
    'Arizona': 'ARI',
    'Atlanta': 'ATL',
    'Baltimore': 'BAL',
    'Buffalo': 'BUF',
    'Carolina': 'CAR',
    'Chicago': 'CHI',
    'Cincinnati': 'CIN',
    'Cleveland': 'CLE',
    'Dallas': 'DAL',
    'Denver': 'DEN',
    'Detroit': 'DET',
    'Green Bay': 'GB',
    'Houston': 'HOU',
    'Indianapolis': 'IND',
    'Jacksonville': 'JAX',
    'Kansas City': 'KC',
    'Miami': 'MIA',
    'Minnesota': 'MIN',
    'New England': 'NE',
    'New Orleans': 'NO',
    'NY Giants': 'NYG',
    'NY Jets': 'NYJ',
    'Philadelphia': 'PHI',
    'Pittsburgh': 'PIT',
    'Seattle': 'SEA',
    'San Francisco': 'SF',
    'Tampa Bay': 'TB',
    'Tennessee': 'TEN',
    'Washington': 'WAS',
    
    # Historical relocations
    'Oakland': 'LV',
    'St Louis': 'LA',
    'San Diego': 'LAC',
    'LA Chargers': 'LAC',
    'LA Rams': 'LA',
    'Los Angeles': 'LA',  # This should work fine now
    'Las Vegas': 'LV',
}





# Convert team and opponent columns
games_odds['team'] = games_odds['team'].map(TEAM_TO_ABBR)
games_odds['opp'] = games_odds['opp'].map(TEAM_TO_ABBR)

# Check for any unmapped teams (will be NaN)
unmapped_teams = games_odds[games_odds['team'].isna() | games_odds['opp'].isna()]
if len(unmapped_teams) > 0:
    print("⚠️  Warning: Found unmapped teams:")
    # Show the ORIGINAL values before mapping
    print(unmapped_teams[['team', 'opp']].drop_duplicates())
    raise ValueError("Fix the TEAM_TO_ABBR mapping to include all teams!")

print(f"✓ All {len(games_odds):,} rows successfully converted")

✓ All 5,432 rows successfully converted

In [121]:
write_to = games_odds.to_parquet('odds_names_norm.parquet')
write_to

In [204]:
odds_data_names_norm = pd.read_parquet('data/raw/odds_names_norm.parquet')
odds_data_names_norm

AttributeError: 'Index' object has no attribute '_format_flat'

      season  game_date team  opp  week   loc  spread  total  money_line  \
0       2025 2025-10-13  WAS  CHI     6  Home    -5.5   49.0        -250
1       2025 2025-10-13  CHI  WAS     6  Away     5.5   49.0         200
2       2025 2025-10-13  ATL  BUF     6  Home     3.5   49.5         177
3       2025 2025-10-13  BUF  ATL     6  Away    -3.5   49.5        -210
4       2025 2025-10-12   KC  DET     6  Home    -2.5   51.0        -150
...      ...        ...  ...  ...   ...   ...     ...    ...         ...
5427    2015 2015-09-13   KC  HOU     1  Away    -1.0   41.0        -115
5428    2015 2015-09-13  CHI   GB     1  Home     6.0   48.5         230
5429    2015 2015-09-13   GB  CHI     1  Away    -6.0   48.5        -290
5430    2015 2015-09-10   NE  PIT     1  Home    -7.0   51.0        -360
5431    2015 2015-09-10  PIT   NE     1  Away     7.0   51.0         280

      conf_game  ...       game_type prev_result days_of_rest  \
0          True  ...  Regular Season         Win          8.0
1          True  ...  Regular Season         Win         15.0
2         False  ...  Regular Season         Win         15.0
3         False  ...  Regular Season        Loss          8.0
4         False  ...  Regular Season        Loss          6.0
...         ...  ...             ...         ...          ...
5427       True  ...  Regular Season  First Game          NaN
5428       True  ...  Regular Season  First Game          NaN
5429       True  ...  Regular Season  First Game          NaN
5430       True  ...  Regular Season  First Game          NaN
5431       True  ...  Regular Season  First Game          NaN

      opp_days_of_rest  rest_advantage  score mov  ats_margin  combined_pts  \
0                 15.0            -7.0  24-25  -1        -6.5            49
1                  8.0             7.0  25-24   1         6.5            49
2                  8.0             7.0  24-14  10        13.5            38
3                 15.0            -7.0  14-24 -10       -13.5            38
4                  7.0            -1.0  30-17  13        10.5            47
...                ...             ...    ...  ..         ...           ...
5427               NaN             0.0  27-20   7         6.0            47
5428               NaN             0.0  23-31  -8        -2.0            54
5429               NaN             0.0  31-23   8         2.0            54
5430               NaN             0.0  28-21   7         0.0            49
5431               NaN             0.0  21-28  -7         0.0            49

      OU_margin
0           0.0
1           0.0
2         -11.5
3         -11.5
4          -4.0
...         ...
5427        6.0
5428        5.5
5429        5.5
5430       -2.0
5431       -2.0

[5432 rows x 21 columns]

In [205]:
print(len(grouped_by_team_week.shape))
print(len(odds_data_names_norm.shape))
odds_data_names_norm
grouped_by_team_week

2
2

AttributeError: 'Index' object has no attribute '_format_flat'

     season  week team season_type opponent_team  completions  attempts  \
0      2025     1  ARI         REG            NO           21        29
32     2025     2  ARI         REG           CAR           17        25
64     2025     3  ARI         REG            SF           22        35
96     2025     4  ARI         REG           SEA           27        41
128    2025     5  ARI         REG           TEN           23        32
..      ...   ...  ...         ...           ...          ...       ...
63     2025     2  WAS         REG            GB           24        42
95     2025     3  WAS         REG            LV           15        21
127    2025     4  WAS         REG           ATL           16        27
155    2025     5  WAS         REG           LAC           15        26
185    2025     6  WAS         REG           CHI           19        26

     passing_yards  passing_tds  passing_interceptions  ...  yards_per_att  \
0              163            2                      0  ...       5.620690
32             220            1                      1  ...       8.800000
64             159            1                      0  ...       4.542857
96             200            2                      2  ...       4.878049
128            220            0                      0  ...       6.875000
..             ...          ...                    ...  ...            ...
63             200            2                      0  ...       4.761905
95             207            1                      0  ...       9.857143
127            156            2                      1  ...       5.777778
155            231            1                      0  ...       8.884615
185            211            3                      1  ...       8.115385

      td_rate  int_rate  sack_rate  rush_ypc  explosive_proxy    off_epa  \
0    0.068966  0.000000   0.147059  5.407407         0.303571  11.460992
32   0.040000  0.040000   0.038462  3.727273         0.319149  14.376126
64   0.028571  0.000000   0.027778  3.785714         0.238095   1.296078
96   0.048780  0.048780   0.127660  5.235294         0.258621   0.779984
128  0.000000  0.000000   0.085714  5.793103         0.295082   4.022022
..        ...       ...        ...       ...              ...        ...
63   0.047619  0.000000   0.086957  2.684211         0.213115 -12.749786
95   0.047619  0.000000   0.045455  6.281250         0.283019  30.342750
127  0.074074  0.037037   0.068966  6.681818         0.326531  10.488719
155  0.038462  0.000000   0.037037  5.821429         0.333333  29.069761
185  0.115385  0.038462   0.103448  4.000000         0.333333   8.801267

     epa_per_play       adot  yac_per_rec
0        0.204661   5.724138     4.761905
32       0.305875   6.400000     6.647059
64       0.020573   5.057143     4.181818
96       0.013448   5.804878     4.629630
128      0.065935   6.531250     5.000000
..            ...        ...          ...
63      -0.209013   6.642857     4.458333
95       0.572505   7.523810     7.533333
127      0.214055  10.592593     1.437500
155      0.538329   9.192308     7.333333
185      0.154408   8.153846     3.684211

[188 rows x 113 columns]

In [209]:
# grouped_by_team_week
# odds_data_names_norm

merged_df = grouped_by_team_week.merge(
    odds_data_names_norm,
    on=['season', 'team', 'week'],
    how='left'
)
merged_df
writing = merged_df.to_parquet(path='D:/proj/howamachinelearns/data/raw/2025/2025_weekly_offense_and_odds.parquet')
writing

In [ ]:
merged_df

['season',
 'week',
 'team',
 'season_type',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'passing_interceptions',
 'sacks_suffered',
 'sack_yards_lost',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_cpoe',
 'passing_2pt_conversions',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'special_teams_tds',
 'def_tackles_solo',
 'def_tackles_with_assist',
 'def_tackle_assists',
 'def_tackles_for_loss',
 'def_tackles_for_loss_yards',
 'def_fumbles_forced',
 'def_sacks',
 'def_sack_yards',
 'def_qb_hits',
 'def_interceptions',
 'def_interception_yards',
 'def_pass_defended',
 'def_tds',
 'def_fumbles',
 'def_safeties',
 'misc_yards',
 'fumble_recovery_own',
 'fumble_recovery_yards_own',
 'fumble_recovery_opp',
 'fumble_recovery_yards_opp',
 'fumble_recovery_tds',
 'penalties',
 'penalty_yards',
 'timeouts',
 'punt_returns',
 'punt_return_yards',
 'kickoff_returns',
 'kickoff_return_yards',
 'fg_made',
 'fg_att',
 'fg_missed',
 'fg_blocked',
 'fg_long',
 'fg_pct',
 'fg_made_0_19',
 'fg_made_20_29',
 'fg_made_30_39',
 'fg_made_40_49',
 'fg_made_50_59',
 'fg_made_60_',
 'fg_missed_0_19',
 'fg_missed_20_29',
 'fg_missed_30_39',
 'fg_missed_40_49',
 'fg_missed_50_59',
 'fg_missed_60_',
 'fg_made_list',
 'fg_missed_list',
 'fg_blocked_list',
 'fg_made_distance',
 'fg_missed_distance',
 'fg_blocked_distance',
 'pat_made',
 'pat_att',
 'pat_missed',
 'pat_blocked',
 'pat_pct',
 'gwfg_made',
 'gwfg_att',
 'gwfg_missed',
 'gwfg_blocked',
 'gwfg_distance',
 'pass_rate',
 'yards_per_att',
 'td_rate',
 'int_rate',
 'sack_rate',
 'rush_ypc',
 'explosive_proxy',
 'off_epa',
 'epa_per_play',
 'adot',
 'yac_per_rec',
 'game_date',
 'opp',
 'loc',
 'spread',
 'total',
 'money_line',
 'conf_game',
 'div_game',
 'game_type',
 'prev_result',
 'days_of_rest',
 'opp_days_of_rest',
 'rest_advantage',
 'score',
 'mov',
 'ats_margin',
 'combined_pts',
 'OU_margin']

### DEFENSE TABLE CREATION

In [210]:
weekly_offense = pd.read_parquet('data/raw/2025/2025_weekly_offense_and_odds.parquet')
print(weekly_offense)
weekly_offense
# print(weekly_offense)

     season  week team season_type opponent_team  completions  attempts  \
0      2025     1  ARI         REG            NO           21        29
1      2025     2  ARI         REG           CAR           17        25
2      2025     3  ARI         REG            SF           22        35
3      2025     4  ARI         REG           SEA           27        41
4      2025     5  ARI         REG           TEN           23        32
..      ...   ...  ...         ...           ...          ...       ...
183    2025     2  WAS         REG            GB           24        42
184    2025     3  WAS         REG            LV           15        21
185    2025     4  WAS         REG           ATL           16        27
186    2025     5  WAS         REG           LAC           15        26
187    2025     6  WAS         REG           CHI           19        26

     passing_yards  passing_tds  passing_interceptions  ...       game_type  \
0              163            2                      0  ...  Regular Season
1              220            1                      1  ...  Regular Season
2              159            1                      0  ...  Regular Season
3              200            2                      2  ...  Regular Season
4              220            0                      0  ...  Regular Season
..             ...          ...                    ...  ...             ...
183            200            2                      0  ...  Regular Season
184            207            1                      0  ...  Regular Season
185            156            2                      1  ...  Regular Season
186            231            1                      0  ...  Regular Season
187            211            3                      1  ...  Regular Season

     prev_result  days_of_rest  opp_days_of_rest  rest_advantage  score   mov  \
0     First Game           NaN               NaN             0.0  20-13   7.0
1            Win           7.0               7.0             0.0  27-22   5.0
2            Win           7.0               7.0             0.0  15-16  -1.0
3           Loss           4.0               4.0             0.0  20-23  -3.0
4           Loss          10.0               7.0             3.0  21-22  -1.0
..           ...           ...               ...             ...    ...   ...
183          Win           4.0               4.0             0.0  18-27  -9.0
184         Loss          10.0               6.0             4.0  41-24  17.0
185          Win           7.0               7.0             0.0  27-34  -7.0
186         Loss           7.0               7.0             0.0  27-10  17.0
187          Win           8.0              15.0            -7.0  24-25  -1.0

     ats_margin  combined_pts  OU_margin
0           1.5          33.0      -11.5
1          -2.0          49.0        3.5
2           0.5          31.0      -13.0
3          -2.0          43.0       -0.5
4          -8.5          43.0        1.5
..          ...           ...        ...
183        -6.0          45.0       -3.0
184        14.0          65.0       21.0
185        -4.0          61.0       17.5
186        20.0          37.0      -11.5
187        -6.5          49.0        0.0

[188 rows x 131 columns]

AttributeError: 'Index' object has no attribute '_format_flat'

     season  week team season_type opponent_team  completions  attempts  \
0      2025     1  ARI         REG            NO           21        29
1      2025     2  ARI         REG           CAR           17        25
2      2025     3  ARI         REG            SF           22        35
3      2025     4  ARI         REG           SEA           27        41
4      2025     5  ARI         REG           TEN           23        32
..      ...   ...  ...         ...           ...          ...       ...
183    2025     2  WAS         REG            GB           24        42
184    2025     3  WAS         REG            LV           15        21
185    2025     4  WAS         REG           ATL           16        27
186    2025     5  WAS         REG           LAC           15        26
187    2025     6  WAS         REG           CHI           19        26

     passing_yards  passing_tds  passing_interceptions  ...       game_type  \
0              163            2                      0  ...  Regular Season
1              220            1                      1  ...  Regular Season
2              159            1                      0  ...  Regular Season
3              200            2                      2  ...  Regular Season
4              220            0                      0  ...  Regular Season
..             ...          ...                    ...  ...             ...
183            200            2                      0  ...  Regular Season
184            207            1                      0  ...  Regular Season
185            156            2                      1  ...  Regular Season
186            231            1                      0  ...  Regular Season
187            211            3                      1  ...  Regular Season

     prev_result  days_of_rest  opp_days_of_rest  rest_advantage  score   mov  \
0     First Game           NaN               NaN             0.0  20-13   7.0
1            Win           7.0               7.0             0.0  27-22   5.0
2            Win           7.0               7.0             0.0  15-16  -1.0
3           Loss           4.0               4.0             0.0  20-23  -3.0
4           Loss          10.0               7.0             3.0  21-22  -1.0
..           ...           ...               ...             ...    ...   ...
183          Win           4.0               4.0             0.0  18-27  -9.0
184         Loss          10.0               6.0             4.0  41-24  17.0
185          Win           7.0               7.0             0.0  27-34  -7.0
186         Loss           7.0               7.0             0.0  27-10  17.0
187          Win           8.0              15.0            -7.0  24-25  -1.0

     ats_margin  combined_pts  OU_margin
0           1.5          33.0      -11.5
1          -2.0          49.0        3.5
2           0.5          31.0      -13.0
3          -2.0          43.0       -0.5
4          -8.5          43.0        1.5
..          ...           ...        ...
183        -6.0          45.0       -3.0
184        14.0          65.0       21.0
185        -4.0          61.0       17.5
186        20.0          37.0      -11.5
187        -6.5          49.0        0.0

[188 rows x 131 columns]

In [164]:
list(weekly_offense)

['season',
 'week',
 'team',
 'season_type',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'passing_interceptions',
 'sacks_suffered',
 'sack_yards_lost',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_cpoe',
 'passing_2pt_conversions',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'special_teams_tds',
 'def_tackles_solo',
 'def_tackles_with_assist',
 'def_tackle_assists',
 'def_tackles_for_loss',
 'def_tackles_for_loss_yards',
 'def_fumbles_forced',
 'def_sacks',
 'def_sack_yards',
 'def_qb_hits',
 'def_interceptions',
 'def_interception_yards',
 'def_pass_defended',
 'def_tds',
 'def_fumbles',
 'def_safeties',
 'misc_yards',
 'fumble_recovery_own',
 'fumble_recovery_yards_own',
 'fumble_recovery_opp',
 'fumble_recovery_yards_opp',
 'fumble_recovery_tds',
 'penalties',
 'penalty_yards',
 'timeouts',
 'punt_returns',
 'punt_return_yards',
 'kickoff_returns',
 'kickoff_return_yards',
 'fg_made',
 'fg_att',
 'fg_missed',
 'fg_blocked',
 'fg_long',
 'fg_pct',
 'fg_made_0_19',
 'fg_made_20_29',
 'fg_made_30_39',
 'fg_made_40_49',
 'fg_made_50_59',
 'fg_made_60_',
 'fg_missed_0_19',
 'fg_missed_20_29',
 'fg_missed_30_39',
 'fg_missed_40_49',
 'fg_missed_50_59',
 'fg_missed_60_',
 'fg_made_list',
 'fg_missed_list',
 'fg_blocked_list',
 'fg_made_distance',
 'fg_missed_distance',
 'fg_blocked_distance',
 'pat_made',
 'pat_att',
 'pat_missed',
 'pat_blocked',
 'pat_pct',
 'gwfg_made',
 'gwfg_att',
 'gwfg_missed',
 'gwfg_blocked',
 'gwfg_distance',
 'pass_rate',
 'yards_per_att',
 'td_rate',
 'int_rate',
 'sack_rate',
 'rush_ypc',
 'explosive_proxy',
 'off_epa',
 'epa_per_play',
 'adot',
 'yac_per_rec',
 'game_date',
 'opp',
 'loc',
 'spread',
 'total',
 'money_line',
 'conf_game',
 'div_game',
 'game_type',
 'prev_result',
 'days_of_rest',
 'opp_days_of_rest',
 'rest_advantage',
 'score',
 'mov',
 'ats_margin',
 'combined_pts',
 'OU_margin']

In [212]:
def_df = weekly_offense.rename(columns={
    "opponent_team":"team",
    "team": "off_team",
    "loc": "off_team_loc",
    "passing_yards": "passing_yards_allowed",
    "passing_air_yards": "passing_air_yards_allowed",
    "passing_yards_after_catch": "passing_yards_after_catch_allowed",
    "passing_tds": "passing_tds_allowed",
    "rushing_yards": "rushing_yards_allowed",
    "rushing_tds": "rushing_tds_allowed",
    "receiving_yards": "receiving_yards_allowed",
    "receiving_tds": "receiving_tds_allowed",
    "off_epa": "def_epa_allowed",
    "epa_per_play": "epa_per_play_allowed",
    "pass_rate": "pass_rate_allowed",
    "yards_per_att": "yards_per_att_allowed",
    "rush_ypc": "rush_ypc_allowed",
    "explosive_proxy": "explosive_allowed",
    "td_rate": "td_rate_allowed",
    "int_rate": "int_rate_forced",
    "sack_rate": "sack_rate_forced",
    "adot": "adot_allowed",
    "yac_per_rec": "yac_per_rec_allowed",
})

# def_df["team"] = def_df["team"]


# print(list(set(def_df.columns) - set(weekly_offense.columns)))



def_df = def_df.merge(weekly_offense[["season","week","opponent_team"]],
                      left_on=["season","week","team"],
                      right_on=["season","week","opponent_team"],
                      how="left")



keep_cols= ["season","week","team","off_team","passing_yards_allowed",
            "off_team_loc",
    "passing_air_yards_allowed",
    "passing_yards_after_catch_allowed",
    "passing_tds_allowed",
    "rushing_yards_allowed",
    "rushing_tds_allowed",
    "receiving_yards_allowed",
    "receiving_tds_allowed",
    "def_sacks",
    "def_qb_hits",
    "def_interceptions",
    "def_fumbles_forced",
    "def_pass_defended",
    "def_tds",
    "def_safeties",
    "def_epa_allowed",
    "epa_per_play_allowed",
    "pass_rate_allowed",
    "yards_per_att_allowed",
    "rush_ypc_allowed",
    "explosive_allowed",
    "td_rate_allowed",
    "int_rate_forced",
    "sack_rate_forced",
    "adot_allowed",
    "yac_per_rec_allowed",
]



def_df = def_df[keep_cols]

def_df

writing = def_df.to_parquet(path='D:/proj/howamachinelearns/data/raw/2025/2025_weekly_defense.parquet')

In [189]:
import pandas as pd
import numpy as np
import os # Assuming this is imported

# -------------------------------------------------------------
# 1. HELPER FUNCTION: Calculations (Single Responsibility)
# -------------------------------------------------------------
def _calculate_metrics(team_stats_df):
    """Calculates all new rate and ratio metrics for the team stats DataFrame."""
    df = team_stats_df.copy()
    
    # Filter to only Regular Season
    df = df[df['season_type'] == 'REG']
    df = df.sort_values(by=['team', 'week'], ascending=True)
    
    attempts = df['attempts']
    total_att_carr = df['attempts'] + df['carries']
    att_sacks_suff = attempts + df['sacks_suffered']
    first_downs = df['passing_first_downs'] + df['rushing_first_downs']

    # Use a common helper for np.divide to simplify
    def safe_divide(numerator, denominator):
        return np.divide(
            numerator, 
            denominator, 
            out=np.zeros_like(numerator, dtype=float), 
            where=denominator != 0
        )

    # Calculate Rates
    df['pass_rate']       = safe_divide(attempts, total_att_carr)
    df['yards_per_att']   = safe_divide(df['passing_yards'], attempts)
    df['td_rate']         = safe_divide(df['passing_tds'], attempts)
    df['int_rate']        = safe_divide(df['passing_interceptions'], attempts)
    df['sack_rate']       = safe_divide(df['sacks_suffered'], att_sacks_suff)
    df['rush_ypc']        = safe_divide(df['rushing_yards'], df['carries'])
    df['explosive_proxy'] = safe_divide(first_downs, total_att_carr)
    df['adot']            = safe_divide(df['passing_air_yards'], attempts)
    df['yac_per_rec']     = safe_divide(df['passing_yards_after_catch'], df['receptions'])
    
    # Calculate EPA metrics
    df['off_epa'] = df['passing_epa'] + df['rushing_epa'] + df['receiving_epa']
    df['epa_per_play'] = safe_divide(df['off_epa'], total_att_carr)
    
    return df

# -------------------------------------------------------------
# 2. MAIN FUNCTION: Orchestration (Handles Flow Control and I/O)
# -------------------------------------------------------------
def process_all_years(years, base_path='data/raw'):
    """
    Loops through years, processes team stats, merges with odds data, 
    and saves the resulting DataFrame to a year-specific Parquet file.
    """
    
    # Load static data ONCE outside the loop (for efficiency)
    try:
        odds_data_names_norm = pd.read_parquet(os.path.join(base_path, 'odds_names_norm.parquet'))
    except Exception as e:
        print(f"Error loading required odds data: {e}")
        return # Exit if a crucial file can't be loaded

    # TEAM_TO_ABBR is defined but not used in the final code logic, 
    # so it can be omitted or moved outside if it's not needed for processing.
    
    for year in years:
        print(f"--- Processing year: {year} ---")
        
        # 1. Setup paths
        season_folder = os.path.join(base_path, str(year))
        os.makedirs(season_folder, exist_ok=True)
        
        # 2. Load year-specific data
        try:
            team_stats_path = os.path.join(base_path, str(year), 'team_stats.parquet')
            team_stats = pd.read_parquet(team_stats_path)
        except Exception as e:
            print(f"Skipping {year}: Could not load team_stats.parquet. Error: {e}")
            continue # Move to the next year
            
        # 3. Process the data (calling the helper function)
        team_stats_processed = _calculate_metrics(team_stats)
        
        # 4. Merge DataFrames
        merged_df = team_stats_processed.merge(
            odds_data_names_norm,
            on=['season', 'team', 'week'],
            how='left'
        )

        # 5. Save the final Parquet file
        file_name = f'{year}_weekly_offense_and_odds.parquet'
        file_path = os.path.join(season_folder, file_name)
        
        try:
            merged_df.to_parquet(file_path, index=False) # Recommend index=False unless index is meaningful
            print(f"SUCCESS: Saved {len(merged_df)} rows to {file_path}")
        except Exception as e:
            print(f"FAILURE: Could not save data for {year}. Error: {e}")

    print("--- Processing complete for all specified years. ---")

In [191]:
# process_all_years(years= (list(range(2016,2025))))

--- Processing year: 2016 ---
SUCCESS: Saved 512 rows to data/raw\2016\2016_weekly_offense_and_odds.parquet
--- Processing year: 2017 ---
SUCCESS: Saved 512 rows to data/raw\2017\2017_weekly_offense_and_odds.parquet
--- Processing year: 2018 ---
SUCCESS: Saved 512 rows to data/raw\2018\2018_weekly_offense_and_odds.parquet
--- Processing year: 2019 ---
SUCCESS: Saved 512 rows to data/raw\2019\2019_weekly_offense_and_odds.parquet
--- Processing year: 2020 ---
SUCCESS: Saved 512 rows to data/raw\2020\2020_weekly_offense_and_odds.parquet
--- Processing year: 2021 ---
SUCCESS: Saved 544 rows to data/raw\2021\2021_weekly_offense_and_odds.parquet
--- Processing year: 2022 ---
SUCCESS: Saved 542 rows to data/raw\2022\2022_weekly_offense_and_odds.parquet
--- Processing year: 2023 ---
SUCCESS: Saved 544 rows to data/raw\2023\2023_weekly_offense_and_odds.parquet
--- Processing year: 2024 ---
SUCCESS: Saved 544 rows to data/raw\2024\2024_weekly_offense_and_odds.parquet
--- Processing complete for all specified years. ---

In [192]:
df = pd.read_parquet('data/raw/2017/2017_weekly_offense_and_odds.parquet')
df

AttributeError: 'Index' object has no attribute '_format_flat'

     season  week team season_type opponent_team  completions  attempts  \
0      2017     1  ARI         REG           DET           27        48
1      2017     2  ARI         REG           IND           19        36
2      2017     3  ARI         REG           DAL           29        48
3      2017     4  ARI         REG            SF           33        51
4      2017     5  ARI         REG           PHI           28        44
..      ...   ...  ...         ...           ...          ...       ...
507    2017    13  WAS         REG           DAL           26        37
508    2017    14  WAS         REG           LAC           15        27
509    2017    15  WAS         REG           ARI           18        26
510    2017    16  WAS         REG           DEN           19        37
511    2017    17  WAS         REG           NYG           20        37

     passing_yards  passing_tds  passing_interceptions  ...       game_type  \
0              268            1                      3  ...  Regular Season
1              332            1                      1  ...  Regular Season
2              325            2                      0  ...  Regular Season
3              357            1                      1  ...  Regular Season
4              291            1                      0  ...  Regular Season
..             ...          ...                    ...  ...             ...
507            251            2                      2  ...  Regular Season
508            151            1                      1  ...  Regular Season
509            196            2                      0  ...  Regular Season
510            299            3                      1  ...  Regular Season
511            158            0                      3  ...  Regular Season

     prev_result  days_of_rest  opp_days_of_rest  rest_advantage  score  mov  \
0     First Game           NaN               NaN             0.0  23-35  -12
1           Loss           7.0               7.0             0.0  16-13    3
2            Win           8.0               8.0             0.0  17-28  -11
3           Loss           6.0              10.0            -4.0  18-15    3
4            Win           7.0               7.0             0.0   7-34  -27
..           ...           ...               ...             ...    ...  ...
507          Win           7.0               7.0             0.0  14-38  -24
508         Loss          10.0               7.0             3.0  13-30  -17
509         Loss           7.0               7.0             0.0  20-15    5
510          Win           7.0              10.0            -3.0  27-11   16
511          Win           7.0               7.0             0.0  10-18   -8

     ats_margin  combined_pts  OU_margin
0         -14.5            58        9.5
1          -3.5            29      -15.0
2          -8.0            45       -1.5
3          -3.5            33      -10.0
4         -21.0            41       -4.0
..          ...           ...        ...
507       -26.0            52        5.0
508       -10.5            43       -3.5
509         1.0            35       -5.0
510        13.0            38       -1.0
511       -13.0            28      -13.0

[512 rows x 131 columns]

In [193]:
import pandas as pd
import os
import glob # Useful for finding files

def calculate_and_save_defense(years, base_path='data/raw'):
    """
    Loops through each year, loads the offense data, transforms it into
    defensive metrics (by renaming columns), and saves the resulting
    defensive DataFrame as a new Parquet file.
    """
    
    # 1. Define the necessary column renames and final column list
    # The team and opponent columns are swapped to shift perspective from offense to defense.
    RENAME_MAP = {
        "opponent_team": "team",         # The opponent team becomes the 'defensive team'
        "team": "off_team",              # The original team becomes the 'offensive team'
        "loc": "off_team_loc",
        
        # Offensive stats become defensive stats allowed
        "passing_yards": "passing_yards_allowed",
        "passing_air_yards": "passing_air_yards_allowed",
        "passing_yards_after_catch": "passing_yards_after_catch_allowed",
        "passing_tds": "passing_tds_allowed",
        "rushing_yards": "rushing_yards_allowed",
        "rushing_tds": "rushing_tds_allowed",
        "receiving_yards": "receiving_yards_allowed",
        "receiving_tds": "receiving_tds_allowed",
        
        # Rate stats become allowed/forced rates
        "off_epa": "def_epa_allowed",
        "epa_per_play": "epa_per_play_allowed",
        "pass_rate": "pass_rate_allowed",
        "yards_per_att": "yards_per_att_allowed",
        "rush_ypc": "rush_ypc_allowed",
        "explosive_proxy": "explosive_allowed",
        "td_rate": "td_rate_allowed",
        "int_rate": "int_rate_forced",  # Renamed to reflect defense forced it
        "sack_rate": "sack_rate_forced", # Renamed to reflect defense forced it
        "adot": "adot_allowed",
        "yac_per_rec": "yac_per_rec_allowed",
    }
    
    # These are the columns to keep and save in the final defensive DataFrame
    FINAL_DEFENSE_COLUMNS = [
        "season", "week", "team", "off_team", "off_team_loc",
        
        # Metrics derived from offense stats
        "passing_yards_allowed", "passing_air_yards_allowed",
        "passing_yards_after_catch_allowed", "passing_tds_allowed",
        "rushing_yards_allowed", "rushing_tds_allowed",
        "receiving_yards_allowed", "receiving_tds_allowed",
        "def_epa_allowed", "epa_per_play_allowed",
        "pass_rate_allowed", "yards_per_att_allowed",
        "rush_ypc_allowed", "explosive_allowed",
        "td_rate_allowed", "int_rate_forced",
        "sack_rate_forced", "adot_allowed",
        "yac_per_rec_allowed",

        # Existing defensive stats that need to be carried over from the original frame
        # NOTE: If these columns (def_sacks, etc.) are NOT in the offense file, 
        # they must be merged in separately from another source or removed from this list.
        "def_sacks", "def_qb_hits", "def_interceptions",
        "def_fumbles_forced", "def_pass_defended",
        "def_tds", "def_safeties", 
    ]


    for year in years:
        print(f"--- Starting defensive processing for {year} ---")
        
        # 1. Define input and output paths
        season_folder = os.path.join(base_path, str(year))
        
        input_file = os.path.join(season_folder, f'{year}_weekly_offense_and_odds.parquet')
        output_file = os.path.join(season_folder, f'{year}_weekly_defense.parquet')
        
        # 2. Check if input file exists
        if not os.path.exists(input_file):
            print(f"File not found: {input_file}. Skipping {year}.")
            continue
            
        # 3. Load the offensive data
        try:
            weekly_offense = pd.read_parquet(input_file)
        except Exception as e:
            print(f"Error loading offense data for {year}: {e}. Skipping.")
            continue
            
        # 4. Create the defensive DataFrame (def_df) by renaming columns
        # This renames columns to shift the perspective from the scoring team to the defending team.
        def_df = weekly_offense.rename(columns=RENAME_MAP)
        
        # 5. Merge Step: Re-add the original team column (now 'off_team') 
        # This step seems redundant given the RENAME_MAP, but it's kept to align with your original logic
        # (It seems you were trying to ensure the offense team name was correctly linked back)
        
        # The key logic here is that for every row in def_df, the "team" (now defense) 
        # must match the "opponent_team" in the original weekly_offense.
        # Since the columns are already renamed in def_df, we just ensure we keep the necessary columns.
        
        # The merge operation you used previously:
        # def_df = def_df.merge(weekly_offense[["season","week","opponent_team"]],
        #                       left_on=["season","week","team"],
        #                       right_on=["season","week","opponent_team"],
        #                       how="left")
        
        # The merge is not necessary here because all required data (the opponent team, now named 'off_team') 
        # is already present and renamed correctly in 'def_df'. 
        
        # 6. Filter to the final, clean set of defensive columns
        # Note: We must check which columns actually exist in the DataFrame after renaming/merging.
        
        # Create a list of columns that are guaranteed to exist after the RENAME_MAP is applied
        existing_cols = list(def_df.columns)
        
        # Filter FINAL_DEFENSE_COLUMNS to only include those present in the DataFrame
        final_cols = [col for col in FINAL_DEFENSE_COLUMNS if col in existing_cols]
        
        # Check for missing defensive stats like 'def_sacks'
        missing_cols = [col for col in FINAL_DEFENSE_COLUMNS if col not in existing_cols and col.startswith('def_')]
        if missing_cols:
            print(f"Warning: Missing core defensive stats in source data for {year}: {missing_cols}")


        def_df = def_df[final_cols]
        
        # 7. Save the final Parquet file
        try:
            def_df.to_parquet(output_file, index=False)
            print(f"SUCCESS: Saved {len(def_df)} rows to {output_file}")
        except Exception as e:
            print(f"FAILURE: Could not save defensive data for {year}. Error: {e}")
            
    print("--- Defensive processing complete for all specified years. ---")

# Example usage (assuming you have the necessary files):
# if __name__ == '__main__':
#     # NOTE: The base_path needs to be the same as the one used in the offense creation
#     calculate_and_save_defense(years=[2022, 2023, 2024], base_path='data/raw')

# calculate_and_save_defense(years=list(range(2016,2025)))

--- Starting defensive processing for 2016 ---
SUCCESS: Saved 512 rows to data/raw\2016\2016_weekly_defense.parquet
--- Starting defensive processing for 2017 ---
SUCCESS: Saved 512 rows to data/raw\2017\2017_weekly_defense.parquet
--- Starting defensive processing for 2018 ---
SUCCESS: Saved 512 rows to data/raw\2018\2018_weekly_defense.parquet
--- Starting defensive processing for 2019 ---
SUCCESS: Saved 512 rows to data/raw\2019\2019_weekly_defense.parquet
--- Starting defensive processing for 2020 ---
SUCCESS: Saved 512 rows to data/raw\2020\2020_weekly_defense.parquet
--- Starting defensive processing for 2021 ---
SUCCESS: Saved 544 rows to data/raw\2021\2021_weekly_defense.parquet
--- Starting defensive processing for 2022 ---
SUCCESS: Saved 542 rows to data/raw\2022\2022_weekly_defense.parquet
--- Starting defensive processing for 2023 ---
SUCCESS: Saved 544 rows to data/raw\2023\2023_weekly_defense.parquet
--- Starting defensive processing for 2024 ---
SUCCESS: Saved 544 rows to data/raw\2024\2024_weekly_defense.parquet
--- Defensive processing complete for all specified years. ---

In [221]:
weekly_offense = pd.read_parquet('data/raw/2024/matchups.parquet')
weekly_offense
# list(weekly_offense.columns)

AttributeError: 'Index' object has no attribute '_format_flat'

     season  week home_team away_team off_team_loc  combined_pts  \
0      2024     2       ARI        LA         home            51
1      2024     3       ARI       DET         home            33
2      2024     4       ARI       WAS         home            56
3      2024     7       ARI       LAC         home            32
4      2024     9       ARI       CHI         home            38
..      ...   ...       ...       ...          ...           ...
262    2024    10       WAS       PIT         home            55
263    2024    12       WAS       DAL         home            60
264    2024    13       WAS       TEN         home            61
265    2024    16       WAS       PHI         home            69
266    2024    17       WAS       ATL         home            54

     home_off_cluster          home_off_cluster_name  home_def_cluster  \
0                   2  Run-Heavy Efficient Explosive                 2
1                   3     Balanced Inefficient Risky                 4
2                   0             Balanced Explosive                 3
3                   1                       Balanced                 2
4                   0             Balanced Explosive                 0
..                ...                            ...               ...
262                 4           Balanced Inefficient                 2
263                 0             Balanced Explosive                 2
264                 2  Run-Heavy Efficient Explosive                 2
265                 1                       Balanced                 1
266                 0             Balanced Explosive                 1

                                home_def_cluster_name  away_off_cluster  \
0                                  Average Strong Run                 4
1                  Leaky Big-Play Risk Red-Zone Leaky                 2
2                                 Leaky Big-Play Risk                 1
3                                  Average Strong Run                 1
4    Stingy High Pressure Ball-Hawking Red-Zone Tough                 4
..                                                ...               ...
262                                Average Strong Run                 0
263                                Average Strong Run                 1
264                                Average Strong Run                 4
265                                  Average Soft Run                 0
266                                  Average Soft Run                 0

             away_off_cluster_name  away_def_cluster  \
0             Balanced Inefficient                 4
1    Run-Heavy Efficient Explosive                 0
2                         Balanced                 1
3                         Balanced                 1
4             Balanced Inefficient                 1
..                             ...               ...
262             Balanced Explosive                 2
263                       Balanced                 1
264           Balanced Inefficient                 3
265             Balanced Explosive                 3
266             Balanced Explosive                 3

                                away_def_cluster_name  \
0                  Leaky Big-Play Risk Red-Zone Leaky
1    Stingy High Pressure Ball-Hawking Red-Zone Tough
2                                    Average Soft Run
3                                    Average Soft Run
4                                    Average Soft Run
..                                                ...
262                                Average Strong Run
263                                  Average Soft Run
264                               Leaky Big-Play Risk
265                               Leaky Big-Play Risk
266                               Leaky Big-Play Risk

    pair_home_off_vs_away_def pair_away_off_vs_home_def
0                         2_4                       4_2
1                         3_0                       2_4
2                         0_1                       1_3
3                         1_1                       1_2
4                         0_1                       4_0
..                        ...                       ...
262                       4_2                       0_2
263                       0_1                       1_2
264                       2_3                       4_2
265                       1_3                       0_1
266                       0_3                       0_1

[267 rows x 16 columns]

In [224]:
x = pd.read_parquet("data/raw/model_dataset.parquet")
x

AttributeError: 'Index' object has no attribute '_format_flat'

      season  week off_team_loc  combined_pts  home_off_cluster  \
0       2015     1         home          50.0                 4
1       2015     1         home          50.0                 0
2       2015     1         home          41.0                 4
3       2015     1         home          54.0                 1
4       2015     1         home          53.0                 1
...      ...   ...          ...           ...               ...
2666    2025     6         home          44.0                 1
2667    2025     6         home          51.0                 1
2668    2025     6         home          32.0                 3
2669    2025     6         home          49.0                 0
2670    2025     6         home          49.0                 1

              home_off_cluster_name  home_def_cluster  \
0     Run-Heavy Efficient Explosive                 1
1          Balanced Explosive Risky                 3
2     Run-Heavy Efficient Explosive                 3
3                          Balanced                 2
4                          Balanced                 1
...                             ...               ...
2666   Balanced Efficient Explosive                 3
2667   Balanced Efficient Explosive                 2
2668                       Balanced                 0
2669  Run-Heavy Efficient Explosive                 2
2670   Balanced Efficient Explosive                 4

                   home_def_cluster_name  away_off_cluster  \
0                                Average                 1
1                                Average                 2
2                                Average                 2
3     Leaky Big-Play Risk Red-Zone Leaky                 4
4                                Average                 1
...                                  ...               ...
2666  Leaky Big-Play Risk Red-Zone Leaky                 1
2667                             Average                 5
2668   Stingy Strong Pass Red-Zone Tough                 2
2669                             Average                 5
2670        Leaky Big-Play Risk Soft Run                 0

              away_off_cluster_name  ...  away_def_yac_per_rec_allowed_last3  \
0                          Balanced  ...                                 NaN
1                          Balanced  ...                                 NaN
2                          Balanced  ...                                 NaN
3     Run-Heavy Efficient Explosive  ...                                 NaN
4                          Balanced  ...                                 NaN
...                             ...  ...                                 ...
2666   Balanced Efficient Explosive  ...                            5.713675
2667     Balanced Inefficient Risky  ...                            4.963675
2668           Balanced Inefficient  ...                            4.906608
2669     Balanced Inefficient Risky  ...                            4.318555
2670  Run-Heavy Efficient Explosive  ...                            4.666667

     away_def_epa_per_play_allowed_last5 away_def_pass_rate_allowed_last5  \
0                                    NaN                              NaN
1                                    NaN                              NaN
2                                    NaN                              NaN
3                                    NaN                              NaN
4                                    NaN                              NaN
...                                  ...                              ...
2666                            0.157326                         0.517264
2667                            0.138789                         0.535196
2668                            0.236391                         0.597057
2669                            0.388113                         0.629206
2670                            0.307404                         0.598341

     away_def_yards_per_att_allowed_last5  away_def_rush_ypc_allowed_last5  \
0                                     NaN                              NaN
1                                     NaN                              NaN
2                                     NaN                              NaN
3                                     NaN                              NaN
4                                     NaN                              NaN
...                                   ...                              ...
2666                             7.114181                         5.568381
2667                             7.035207                         4.971182
2668                             7.403396                         3.958672
2669                             8.268850                         5.061509
2670                             7.707957                         5.947751

      away_def_explosive_allowed_last5  away_def_adot_allowed_last5  \
0                                  NaN                          NaN
1                                  NaN                          NaN
2                                  NaN                          NaN
3                                  NaN                          NaN
4                                  NaN                          NaN
...                                ...                          ...
2666                          0.324402                     7.998475
2667                          0.318709                     8.002578
2668                          0.299122                     8.347340
2669                          0.371576                     8.760553
2670                          0.400250                     8.413113

      away_def_yac_per_rec_allowed_last5  te_pair_home_off_vs_away_def  \
0                                    NaN                           NaN
1                                    NaN                           NaN
2                                    NaN                     50.000000
3                                    NaN                           NaN
4                                    NaN                           NaN
...                                  ...                           ...
2666                            5.196626                     49.428571
2667                            5.444872                           NaN
2668                            4.860631                     43.400000
2669                            4.517706                     55.625000
2670                            4.591133                     48.750000

      te_pair_away_off_vs_home_def
0                              NaN
1                              NaN
2                        50.000000
3                              NaN
4                        50.000000
...                            ...
2666                     58.333333
2667                     49.833333
2668                     40.230769
2669                     50.000000
2670                     59.333333

[2671 rows x 128 columns]